import { DashboardLayout } from "@/components/dashboard/dashboard-layout";

export default async function DashboardPage() {
  // Demo data - no auth required
  const userData = {
    displayName: "Builder",
    avatarUrl: undefined,
    about: "Building amazing projects with Codyssey",
    stats: {
      level: 1,
      xp: 0,
      xpToNextLevel: 100,
      tasksCompleted: 0,
      totalTasks: 15,
    },
  };

  // Demo project
  const projectData = {
    id: "demo-1",
    name: "My First Project",
    description: "My First Project - Building something amazing with Codyssey",
    goal: "Launch in 30 days",
    location: "Massachusetts, United States",
    links: {},
  };

  // Demo levels
  const levels = [
    {
      id: 1,
      title: "Spark",
      description: "Ignite your idea",
      xpRequired: 0,
      unlocked: true,
      completed: false,
      current: true,
    },
    {
      id: 2,
      title: "Build Prep",
      description: "Prepare your foundation",
      xpRequired: 100,
      unlocked: true,
      completed: false,
      current: false,
    },
    {
      id: 3,
      title: "Core Build",
      description: "Create your MVP",
      xpRequired: 250,
      unlocked: true,
      completed: false,
      current: false,
    },
    {
      id: 4,
      title: "Launch",
      description: "Ship to the world",
      xpRequired: 500,
      unlocked: true,
      completed: false,
      current: false,
    },
    {
      id: 5,
      title: "Grow",
      description: "Scale and iterate",
      xpRequired: 1000,
      unlocked: true,
      completed: false,
      current: false,
    },
  ];

  // Demo tasks - comprehensive list for all 5 levels (15 steps)
  const tasks = [
    // ===== LEVEL 1: SPARK =====
    // L1S1: Problem & Market Scan
    {
      id: "define-problem",
      title: "Define the Problem",
      description: "Clearly articulate the problem you're solving",
      xp_reward: 50,
      required: true,
      status: "todo" as const,
    },
    {
      id: "research-competition",
      title: "Research Competition",
      description: "Analyze your top 3 competitors",
      xp_reward: 50,
      required: true,
      status: "todo" as const,
    },
    {
      id: "identify-target-audience",
      title: "Identify Target Audience",
      description: "Define who your users are",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    {
      id: "market-size-analysis",
      title: "Market Size Analysis",
      description: "Estimate your addressable market",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    // L1S2: Hypotheses & Validation
    {
      id: "brainstorm-solutions",
      title: "Brainstorm Solutions",
      description: "Create 3+ solution hypotheses",
      xp_reward: 50,
      required: true,
      status: "todo" as const,
    },
    {
      id: "validate-idea",
      title: "Validate with Users",
      description: "Interview 5+ users to test assumptions",
      xp_reward: 50,
      required: true,
      status: "todo" as const,
    },
    {
      id: "user-interview-analysis",
      title: "Analyze Interview Notes",
      description: "Extract insights and patterns",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    {
      id: "create-value-hypothesis",
      title: "Create Value Hypothesis",
      description: "Write your value proposition",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    // L1S3: MVP Scope
    {
      id: "define-mvp-scope",
      title: "Define MVP Scope",
      description: "Lock in 3-5 core features",
      xp_reward: 50,
      required: true,
      status: "todo" as const,
    },
    {
      id: "create-user-stories",
      title: "Create User Stories",
      description: "Write user-centric feature descriptions",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    {
      id: "design-success-metrics",
      title: "Design Success Metrics",
      description: "Define how you'll measure success",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },

    // ===== LEVEL 2: BUILD PREP =====
    // L2S1: Stack & Architecture
    {
      id: "choose-tech-stack",
      title: "Choose Tech Stack",
      description: "Select frontend, backend, and database",
      xp_reward: 50,
      required: true,
      status: "todo" as const,
    },
    {
      id: "design-architecture",
      title: "Design Architecture",
      description: "Create system architecture diagram",
      xp_reward: 50,
      required: true,
      status: "todo" as const,
    },
    {
      id: "document-dependencies",
      title: "Document Dependencies",
      description: "List all libraries and services",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    {
      id: "identify-tech-risks",
      title: "Identify Tech Risks",
      description: "Spot potential technical challenges",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    // L2S2: Wireframes & Design
    {
      id: "create-wireframes",
      title: "Create Wireframes",
      description: "Sketch core user flows",
      xp_reward: 50,
      required: true,
      status: "todo" as const,
    },
    {
      id: "design-ui-system",
      title: "Design UI System",
      description: "Define colors, typography, components",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    {
      id: "create-user-flows",
      title: "Create User Flows",
      description: "Map out user journey diagrams",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    // L2S3: Repo & Milestones
    {
      id: "setup-repository",
      title: "Setup Repository",
      description: "Initialize Git repo and structure",
      xp_reward: 50,
      required: true,
      status: "todo" as const,
    },
    {
      id: "define-data-model",
      title: "Define Data Model",
      description: "Design database schema",
      xp_reward: 50,
      required: true,
      status: "todo" as const,
    },
    {
      id: "plan-milestones",
      title: "Plan Milestones",
      description: "Break MVP into 2-4 weekly goals",
      xp_reward: 50,
      required: true,
      status: "todo" as const,
    },
    {
      id: "setup-ci-cd",
      title: "Setup CI/CD",
      description: "Configure automated deployments",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    {
      id: "create-deployment-plan",
      title: "Create Deployment Plan",
      description: "Plan production infrastructure",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    {
      id: "write-api-specs",
      title: "Write API Specs",
      description: "Document API endpoints",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },

    // ===== LEVEL 3: CORE BUILD =====
    // L3S1: Foundation
    {
      id: "setup-dev-environment",
      title: "Setup Dev Environment",
      description: "Configure local development setup",
      xp_reward: 50,
      required: true,
      status: "todo" as const,
    },
    {
      id: "build-auth",
      title: "Build Authentication",
      description: "Implement signup/login flow",
      xp_reward: 50,
      required: true,
      status: "todo" as const,
    },
    {
      id: "build-core-feature-1",
      title: "Build Core Feature #1",
      description: "Ship your first main feature",
      xp_reward: 50,
      required: true,
      status: "todo" as const,
    },
    {
      id: "setup-logging-monitoring",
      title: "Setup Logging & Monitoring",
      description: "Add error tracking and logs",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    {
      id: "document-setup-guide",
      title: "Document Setup Guide",
      description: "Write README and setup instructions",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    // L3S2: Features & UI
    {
      id: "build-core-feature-2",
      title: "Build Core Feature #2",
      description: "Ship your second main feature",
      xp_reward: 50,
      required: true,
      status: "todo" as const,
    },
    {
      id: "build-core-feature-3",
      title: "Build Core Feature #3",
      description: "Ship your third main feature",
      xp_reward: 50,
      required: true,
      status: "todo" as const,
    },
    {
      id: "implement-ui",
      title: "Implement UI Design",
      description: "Apply design system to all pages",
      xp_reward: 50,
      required: true,
      status: "todo" as const,
    },
    {
      id: "add-animations",
      title: "Add Animations",
      description: "Polish with micro-interactions",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    {
      id: "implement-accessibility",
      title: "Implement Accessibility",
      description: "Ensure WCAG compliance",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    {
      id: "optimize-performance",
      title: "Optimize Performance",
      description: "Improve load times and responsiveness",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    // L3S3: Hardening & Tests
    {
      id: "write-tests",
      title: "Write Tests",
      description: "Add unit and integration tests",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    {
      id: "setup-error-boundaries",
      title: "Setup Error Boundaries",
      description: "Handle errors gracefully",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    {
      id: "create-demo-data",
      title: "Create Demo Data",
      description: "Add sample data for testing",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    {
      id: "performance-audit",
      title: "Performance Audit",
      description: "Run performance testing",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },

    // ===== LEVEL 4: LAUNCH =====
    // L4S1: Deployment
    {
      id: "deploy-production",
      title: "Deploy to Production",
      description: "Go live with your app",
      xp_reward: 50,
      required: true,
      status: "todo" as const,
    },
    {
      id: "setup-analytics",
      title: "Setup Analytics",
      description: "Track user behavior and events",
      xp_reward: 50,
      required: true,
      status: "todo" as const,
    },
    {
      id: "setup-monitoring",
      title: "Setup Monitoring",
      description: "Configure uptime and error alerts",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    {
      id: "setup-customer-support",
      title: "Setup Customer Support",
      description: "Add help desk or chat widget",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    // L4S2: Landing & Content
    {
      id: "create-landing-page",
      title: "Create Landing Page",
      description: "Build compelling homepage",
      xp_reward: 50,
      required: true,
      status: "todo" as const,
    },
    {
      id: "write-launch-content",
      title: "Write Launch Content",
      description: "Craft tweets, emails, and posts",
      xp_reward: 50,
      required: true,
      status: "todo" as const,
    },
    {
      id: "create-demo-video",
      title: "Create Demo Video",
      description: "Record product walkthrough",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    {
      id: "design-launch-assets",
      title: "Design Launch Assets",
      description: "Create social media graphics",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    // L4S3: Launch & Feedback
    {
      id: "launch-product",
      title: "Launch Product",
      description: "Ship on Product Hunt, Twitter, HN",
      xp_reward: 50,
      required: true,
      status: "todo" as const,
    },
    {
      id: "gather-feedback",
      title: "Gather Feedback",
      description: "Talk to first 10+ users",
      xp_reward: 50,
      required: true,
      status: "todo" as const,
    },
    {
      id: "create-press-kit",
      title: "Create Press Kit",
      description: "Prepare media resources",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    {
      id: "build-email-list",
      title: "Build Email List",
      description: "Setup newsletter and capture leads",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    {
      id: "community-engagement",
      title: "Community Engagement",
      description: "Join relevant communities",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },

    // ===== LEVEL 5: GROW =====
    // L5S1: Metrics & Growth
    {
      id: "analyze-metrics",
      title: "Analyze Metrics",
      description: "Review analytics and user behavior",
      xp_reward: 50,
      required: true,
      status: "todo" as const,
    },
    {
      id: "plan-growth-experiments",
      title: "Plan Growth Experiments",
      description: "Design A/B tests and improvements",
      xp_reward: 50,
      required: true,
      status: "todo" as const,
    },
    {
      id: "cohort-analysis",
      title: "Cohort Analysis",
      description: "Track user retention by cohort",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    {
      id: "competitive-benchmarking",
      title: "Competitive Benchmarking",
      description: "Compare metrics to competitors",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    // L5S2: Activation & Retention
    {
      id: "optimize-onboarding",
      title: "Optimize Onboarding",
      description: "Reduce time to 'aha moment'",
      xp_reward: 50,
      required: true,
      status: "todo" as const,
    },
    {
      id: "improve-retention",
      title: "Improve Retention",
      description: "Build habit loops and reminders",
      xp_reward: 50,
      required: true,
      status: "todo" as const,
    },
    {
      id: "implement-push-notifications",
      title: "Implement Push Notifications",
      description: "Add email/push notification system",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    {
      id: "build-habit-loops",
      title: "Build Habit Loops",
      description: "Create triggers and rewards",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    {
      id: "create-aha-moment",
      title: "Create Aha Moment",
      description: "Define and optimize first-value experience",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    // L5S3: Scale & Referrals
    {
      id: "reach-100-users",
      title: "Reach 100 Users",
      description: "Hit your first growth milestone",
      xp_reward: 50,
      required: true,
      status: "todo" as const,
    },
    {
      id: "build-referral-system",
      title: "Build Referral System",
      description: "Add invite and reward mechanics",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    {
      id: "create-pricing-strategy",
      title: "Create Pricing Strategy",
      description: "Design monetization model",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    {
      id: "launch-paid-tier",
      title: "Launch Paid Tier",
      description: "Ship premium features",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
    {
      id: "plan-next-features",
      title: "Plan Next Features",
      description: "Roadmap for next phase",
      xp_reward: 30,
      required: false,
      status: "todo" as const,
    },
  ];

  return <DashboardLayout user={userData} project={projectData} levels={levels} tasks={tasks} />;
}

